//! `generated/css/*.css` — one file per theme plus a bundle.
//!
//! These are **neutral** custom properties (`--colony-*`), not Discord or Angular
//! specific. Each consumer maps `--colony-*` onto its own variable names in its
//! own repo; that mapping is the consumer's business, the values are ours.

use std::fmt::Write as _;

use crate::model::{Family, Tokens, Variant};

/// A single theme's rule block.
pub fn render_variant(family: &Family, variant: &Variant) -> String {
    let slug = variant.slug(family);
    let mut out = String::with_capacity(2048);

    let _ = writeln!(out, "/*");
    let _ = writeln!(out, " * Project Colony — {}", variant.display_name(family));
    let _ = writeln!(
        out,
        " * @generated by colony-tokens from tokens/families/{}.toml — DO NOT EDIT.",
        family.key
    );
    let _ = writeln!(out, " */");
    let _ = writeln!(out, "[data-colony-theme=\"{slug}\"],");
    let _ = writeln!(out, ".colony-theme-{slug} {{");
    let _ = writeln!(out, "  color-scheme: {};", variant.mode.as_str());

    let mut group = "";
    for (field, color) in variant.palette.entries() {
        if field.group != group {
            group = field.group;
            let _ = writeln!(out, "\n  /* {group} */");
        }
        let _ = writeln!(out, "  {}: {};", field.css_var(), color);
    }

    let _ = writeln!(out, "}}");
    out
}

/// The accent overrides, as a `:root` block. Theme-independent, so it is safe
/// to load once alongside any single theme file.
pub fn render_accents(tokens: &Tokens) -> String {
    let mut out = String::with_capacity(1024);
    let _ = writeln!(out, "/*");
    let _ = writeln!(out, " * Project Colony — accent overrides");
    let _ = writeln!(
        out,
        " * @generated by colony-tokens from tokens/accents.toml — DO NOT EDIT."
    );
    let _ = writeln!(out, " *");
    let _ = writeln!(
        out,
        " * Palette-independent. Load alongside a theme; \"auto\" means no override,"
    );
    let _ = writeln!(out, " * i.e. keep the theme's own --colony-accent-blue.");
    let _ = writeln!(out, " */");
    let _ = writeln!(out, ":root {{");
    for accent in &tokens.accents {
        let _ = writeln!(out, "  --colony-accent-{}: {};", accent.key, accent.color);
    }
    let _ = writeln!(out, "}}");
    out
}

/// All themes in one file, for consumers that ship a single stylesheet.
pub fn render_bundle(tokens: &Tokens) -> String {
    let mut out = String::with_capacity(256 * 1024);
    let _ = writeln!(out, "/*");
    let _ = writeln!(
        out,
        " * Project Colony — every theme ({} families, {} variants).",
        tokens.families.len(),
        tokens.variant_count()
    );
    let _ = writeln!(
        out,
        " * @generated by colony-tokens from tokens/families/*.toml — DO NOT EDIT."
    );
    let _ = writeln!(out, " *");
    let _ = writeln!(
        out,
        " * Apply a theme by setting [data-colony-theme=\"<family>-<variant>\"] on a"
    );
    let _ = writeln!(
        out,
        " * root element, or by adding the matching .colony-theme-* class."
    );
    let _ = writeln!(out, " */");

    for (family, variant) in tokens.variants() {
        out.push('\n');
        // The bundle repeats each block without its own file header.
        let block = render_variant(family, variant);
        let body = block
            .split_once("*/\n")
            .map(|(_, rest)| rest)
            .unwrap_or(&block);
        let _ = writeln!(out, "/* {} */", variant.display_name(family));
        out.push_str(body);
    }
    out
}
