//! `generated/themes.json` — the machine-readable bundle every non-Rust
//! consumer reads instead of scraping Rust source.

use serde_json::{json, Map, Value};

use crate::model::{Palette, Tokens};

/// Bumped when the shape changes in a way that breaks existing readers.
pub const SCHEMA_VERSION: u32 = 1;

pub fn render(tokens: &Tokens) -> Value {
    let fields: Vec<Value> = Palette::FIELDS
        .iter()
        .map(|f| {
            json!({
                "name": f.name,
                "group": f.group,
                "cssVar": f.css_var(),
            })
        })
        .collect();

    let families: Vec<Value> = tokens
        .families
        .iter()
        .map(|family| {
            let variants: Vec<Value> = family
                .variants
                .iter()
                .map(|variant| {
                    let mut palette = Map::new();
                    for (field, color) in variant.palette.entries() {
                        palette.insert(field.name.to_string(), json!(color.to_css_hex()));
                    }
                    json!({
                        "key": variant.key,
                        "slug": variant.slug(family),
                        "const": variant.const_name,
                        "labelKey": variant.label_key,
                        "label": { "fr": variant.label.fr, "en": variant.label.en },
                        "mode": variant.mode.as_str(),
                        "swatch": {
                            "bg": variant.swatch.bg.to_css_hex(),
                            "accent": variant.swatch.accent.to_css_hex(),
                        },
                        "notes": variant.notes,
                        // Reported, not enforced: consumers can surface a warning
                        // without recomputing WCAG maths themselves.
                        "contrast": {
                            "textPrimaryOnBgPrimary": round2(
                                variant.palette.text_primary.contrast(variant.palette.bg_primary)
                            ),
                            "textMutedOnBgPrimary": round2(
                                variant.palette.text_muted.contrast(variant.palette.bg_primary)
                            ),
                        },
                        "palette": Value::Object(palette),
                    })
                })
                .collect();

            json!({
                "key": family.key,
                "order": family.order,
                "labelKey": family.label_key,
                "label": { "fr": family.label.fr, "en": family.label.en },
                "icon": family.icon,
                "notes": family.notes,
                "variants": variants,
            })
        })
        .collect();

    let accents: Vec<Value> = tokens
        .accents
        .iter()
        .map(|a| {
            json!({
                "key": a.key,
                "labelKey": a.label_key,
                "label": { "fr": a.label.fr, "en": a.label.en },
                "color": a.color.to_css_hex(),
                "cssVar": format!("--colony-accent-{}", a.key),
            })
        })
        .collect();

    json!({
        "schemaVersion": SCHEMA_VERSION,
        "source": "https://github.com/Project-Colony/Project-Colony-Resources",
        "note": "@generated by colony-tokens from tokens/families/*.toml — DO NOT EDIT.",
        "familyCount": tokens.families.len(),
        "variantCount": tokens.variant_count(),
        "fields": fields,
        // Order is load-bearing; see tokens/accents.toml.
        "accents": accents,
        "families": families,
    })
}

fn round2(v: f64) -> f64 {
    (v * 100.0).round() / 100.0
}
