//! `generated/colony.schema.json` — a JSON Schema for a repository's
//! `colony.json`, derived from the types in `crate::manifest`.
//!
//! Point an editor at it with:
//!
//! ```json
//! { "$schema": "https://raw.githubusercontent.com/Project-Colony/Project-Colony-Resources/main/generated/colony.schema.json" }
//! ```

use serde_json::{json, Map, Value};

use crate::manifest::{Category, CATEGORIES, PLATFORMS, PLATFORM_ASSET_SUFFIXES};

pub fn render() -> Value {
    let release_entry = json!({
        "type": "object",
        "description":
            "Which asset to fetch for this platform, and how to treat it once downloaded.",
        "properties": {
            "tag": {
                "type": "string",
                "minLength": 1,
                "description":
                    "A git tag, or the literal \"latest\" to always track the newest release.",
            },
            "file": {
                "type": "string",
                "minLength": 1,
                "description":
                    "Exact asset filename. Mutually exclusive with filePattern.",
            },
            "filePattern": {
                "type": "string",
                "minLength": 1,
                "description":
                    "Case-insensitive pattern matched against the release's asset names, \
                     for assets whose name carries the version. Must match exactly one asset.",
            },
            "binary": {
                "type": "string",
                "minLength": 1,
                "description":
                    "Binary to extract from inside the downloaded archive (.zip / .tar.gz). \
                     Omit when the downloaded file is itself the binary.",
            },
            "sha256": {
                "type": "string",
                "pattern": "^[0-9a-f]{64}$",
                "description": "Optional SHA-256 of the asset, 64 lowercase hex characters.",
            },
        },
        "required": ["tag"],
        "additionalProperties": false,
        // Colony reads both fields but cannot act on both; make the schema say so.
        "oneOf": [
            { "required": ["file"], "not": { "required": ["filePattern"] } },
            { "required": ["filePattern"], "not": { "required": ["file"] } },
        ],
    });

    let mut release_files = Map::new();
    for platform in PLATFORMS {
        release_files.insert((*platform).to_string(), release_entry.clone());
    }

    let convention_hint = PLATFORM_ASSET_SUFFIXES
        .iter()
        .map(|(platform, suffix)| format!("{platform}: <repo>{suffix}"))
        .collect::<Vec<_>>()
        .join(", ");

    json!({
        "$schema": "https://json-schema.org/draft/2020-12/schema",
        "$id": "https://github.com/Project-Colony/Project-Colony-Resources/generated/colony.schema.json",
        "title": "colony.json",
        "description":
            "@generated by colony-tokens — DO NOT EDIT. The manifest a Project Colony \
             repository ships at its root so the launcher can list and install it.",
        "type": "object",
        "properties": {
            "$schema": { "type": "string" },
            "name": {
                "type": "string",
                "minLength": 1,
                "description":
                    "Display name in the launcher. May differ from the repository name — \
                     this is the only field the user actually reads.",
            },
            "category": {
                "type": "string",
                "description": format!(
                    "Which section of the launcher files this program. Matched \
                     case-insensitively. Colony warns and ignores an unrecognized value, \
                     which files the program nowhere. Canonical values: {}.",
                    CATEGORIES.iter().map(|c| c.canonical).collect::<Vec<_>>().join(", ")
                ),
                "enum": Category::all_spellings(),
            },
            "platforms": {
                "type": "array",
                "description": format!(
                    "Leave empty to let Colony auto-detect from release asset names \
                     following the convention ({convention_hint}). \
                     \"macos\" is Apple Silicon, \"macos-x86\" is Intel."
                ),
                "items": { "enum": PLATFORMS },
                "uniqueItems": true,
            },
            "releaseFiles": {
                "type": "object",
                "description":
                    "Explicit per-platform asset resolution. Only needed when the assets do \
                     not follow the naming convention, or when installing from an archive. \
                     If present, it must cover every declared platform.",
                "properties": Value::Object(release_files),
                "additionalProperties": false,
            },
            "icon": {
                "type": "string",
                "pattern": "^(?!/).*\\.(png|PNG)$",
                "description":
                    "Repo-relative path to a square PNG. When absent, Colony probes icon.png \
                     at the repo root, then falls back to a category hexagon tinted by the \
                     program's name.",
            },
            "signed": {
                "type": "boolean",
                "description":
                    "Require a valid detached ed25519 signature for every asset. When true, a \
                     missing or invalid <asset>.sig aborts the install instead of falling \
                     back to the unsigned path.",
            },
        },
        "required": ["name", "category"],
        "additionalProperties": false,
    })
}
