//! `crates/colony-ui/src/generated/palettes.rs` — palettes, the resolver and
//! the picker table.
//!
//! Inside the crate, not under the top-level `generated/`: `cargo package` only
//! ships files under the crate root, so anything outside it is missing from a
//! published crate and fails to build for whoever downloads it.

use std::fmt::Write as _;

use crate::model::{Tokens, Variant};

const HEADER: &str = "\
// @generated by colony-tokens from tokens/ — DO NOT EDIT.
//
// Regenerate with:  cargo run -p colony-tokens -- generate
//
// This file is meant to be `include!`d from a module that already has in scope:
//   - `ThemePalette`, the 38-field palette struct
//   - `hex(u32) -> Color`, the const-fn hex literal helper
//   - `Color`, iced's colour type
//
// It defines:
//   - one `ThemePalette` const per theme variant
//   - `THEME_FAMILIES`, the ordered catalog the Settings picker renders
//   - `resolve(family, variant)` and `FALLBACK_PALETTE`, the config lookup
//   - `ACCENT_OVERRIDES` and `accent_key_to_color(key)`, the accent picker
";

pub fn render(tokens: &Tokens) -> String {
    let mut out = String::with_capacity(128 * 1024);
    out.push_str(HEADER);

    render_palettes(&mut out, tokens);
    render_catalog(&mut out, tokens);
    render_resolver(&mut out, tokens);
    render_accents(&mut out, tokens);

    out
}

fn render_accents(out: &mut String, tokens: &Tokens) {
    out.push_str(
        "
/// A palette-independent accent the user can pick in Settings → Appearance →
/// Colors, overriding the active theme's own accent.
#[derive(Debug, Clone, Copy)]
pub struct AccentOverride {
    pub key: &'static str,
    pub label_key: &'static str,
    pub color: u32,
}

/// The accent overrides, in the order Colony's per-app identity tint hashes
/// into. APPEND-ONLY: reordering this list re-colours every installed app's
/// icon on every user's machine.
pub const ACCENT_OVERRIDES: &[AccentOverride] = &[
",
    );
    for accent in &tokens.accents {
        let _ = writeln!(out, "    AccentOverride {{");
        let _ = writeln!(out, "        key: {:?},", accent.key);
        let _ = writeln!(out, "        label_key: {:?},", accent.label_key);
        let _ = writeln!(out, "        color: {},", accent.color.to_rust_hex());
        let _ = writeln!(out, "    }},");
    }
    out.push_str("];\n");

    out.push_str(
        "
/// Resolve an accent key to its colour. `None` means \"auto\" — the caller
/// should fall back to the active palette's own `accent_blue`.
pub fn accent_key_to_color(key: &str) -> Option<Color> {
    ACCENT_OVERRIDES
        .iter()
        .find(|a| a.key == key)
        .map(|a| hex(a.color))
}
",
    );
}

fn render_palettes(out: &mut String, tokens: &Tokens) {
    out.push_str("\nimpl ThemePalette {\n");

    let mut first = true;
    let mut current_family = "";
    for (family, variant) in tokens.variants() {
        if !first {
            out.push('\n');
        }
        first = false;

        if family.key != current_family {
            current_family = &family.key;
            if let Some(notes) = &family.notes {
                for line in wrap(&format!("{} — {}", family.label.en, notes), 72) {
                    let _ = writeln!(out, "    // {line}");
                }
            }
        }

        let _ = writeln!(out, "    /// {}.", variant.display_name(family));
        if let Some(notes) = &variant.notes {
            let _ = writeln!(out, "    ///");
            for line in wrap(notes, 68) {
                let _ = writeln!(out, "    /// {line}");
            }
        }
        let _ = writeln!(out, "    pub const {}: Self = Self {{", variant.const_name);

        let mut group = "";
        for (field, color) in variant.palette.entries() {
            if field.group != group {
                if !group.is_empty() {
                    out.push('\n');
                }
                group = field.group;
            }
            let _ = writeln!(out, "        {}: hex({}),", field.name, color.to_rust_hex());
        }
        out.push_str("    };\n");
    }

    out.push_str("}\n");
}

fn render_catalog(out: &mut String, tokens: &Tokens) {
    out.push_str(
        "
/// One selectable variant inside a family, as shown in the Settings picker.
#[derive(Debug, Clone, Copy)]
pub struct ThemeVariantMeta {
    /// Stable key stored in the user's config, e.g. `\"dark\"`.
    pub key: &'static str,
    /// i18n key for the variant's display name.
    pub label_key: &'static str,
    /// `\"light\"` or `\"dark\"`, derived from `bg_primary`'s luminance.
    pub mode: &'static str,
    /// Background drawn on the picker card.
    pub swatch_bg: u32,
    /// Accent drawn on the picker card.
    pub swatch_accent: u32,
    /// The palette this variant selects.
    pub palette: ThemePalette,
}

/// A theme family, i.e. one row of the Settings picker.
#[derive(Debug, Clone, Copy)]
pub struct ThemeFamilyMeta {
    /// Stable key stored in the user's config, e.g. `\"gruvbox\"`.
    pub key: &'static str,
    /// i18n key for the family's display name.
    pub label_key: &'static str,
    /// Nerd Font glyph, or `\"\"` when the family has none.
    pub icon: &'static str,
    pub variants: &'static [ThemeVariantMeta],
}

",
    );

    // Per-family variant slices, so THEME_FAMILIES can borrow them as 'static.
    for family in &tokens.families {
        let _ = writeln!(
            out,
            "const {}_VARIANTS: &[ThemeVariantMeta] = &[",
            family.key.to_uppercase()
        );
        for variant in &family.variants {
            let _ = writeln!(out, "    ThemeVariantMeta {{");
            let _ = writeln!(out, "        key: {:?},", variant.key);
            let _ = writeln!(out, "        label_key: {:?},", variant.label_key);
            let _ = writeln!(out, "        mode: {:?},", variant.mode.as_str());
            let _ = writeln!(
                out,
                "        swatch_bg: {},",
                variant.swatch.bg.to_rust_hex()
            );
            let _ = writeln!(
                out,
                "        swatch_accent: {},",
                variant.swatch.accent.to_rust_hex()
            );
            let _ = writeln!(
                out,
                "        palette: ThemePalette::{},",
                variant.const_name
            );
            let _ = writeln!(out, "    }},");
        }
        out.push_str("];\n\n");
    }

    let _ = writeln!(
        out,
        "/// Every theme family, in the order the Settings picker renders them\n\
         /// ({} families, {} variants).",
        tokens.families.len(),
        tokens.variant_count()
    );
    out.push_str("pub const THEME_FAMILIES: &[ThemeFamilyMeta] = &[\n");
    for family in &tokens.families {
        let _ = writeln!(out, "    ThemeFamilyMeta {{");
        let _ = writeln!(out, "        key: {:?},", family.key);
        let _ = writeln!(out, "        label_key: {:?},", family.label_key);
        let _ = writeln!(out, "        icon: \"{}\",", family.icon_rust_escape());
        let _ = writeln!(
            out,
            "        variants: {}_VARIANTS,",
            family.key.to_uppercase()
        );
        let _ = writeln!(out, "    }},");
    }
    out.push_str("];\n");
}

fn render_resolver(out: &mut String, tokens: &Tokens) {
    let fallback = fallback_variant(tokens);

    out.push_str(
        "
/// The palette used when a config names a theme this build does not know —
/// an older config, a hand-edited file, or a family that was removed.
",
    );
    let _ = writeln!(
        out,
        "pub const FALLBACK_PALETTE: ThemePalette = ThemePalette::{};\n",
        fallback.const_name
    );

    out.push_str(
        "/// Resolve a `(family, variant)` pair to its palette, falling back to\n\
         /// [`FALLBACK_PALETTE`] for anything unrecognized.\n\
         pub fn resolve(family: &str, variant: &str) -> ThemePalette {\n    \
         match (family, variant) {\n",
    );
    for (family, variant) in tokens.variants() {
        let _ = writeln!(
            out,
            "        ({:?}, {:?}) => ThemePalette::{},",
            family.key, variant.key, variant.const_name
        );
    }
    out.push_str("        _ => FALLBACK_PALETTE,\n    }\n}\n");
}

/// Greedy word wrap, so long design notes stay readable as doc comments.
fn wrap(text: &str, width: usize) -> Vec<String> {
    let mut lines = Vec::new();
    let mut current = String::new();
    for word in text.split_whitespace() {
        if !current.is_empty() && current.len() + 1 + word.len() > width {
            lines.push(std::mem::take(&mut current));
        }
        if !current.is_empty() {
            current.push(' ');
        }
        current.push_str(word);
    }
    if !current.is_empty() {
        lines.push(current);
    }
    lines
}

/// Colony's historical fallback is Gruvbox Dark; keep it when present so an
/// existing install resolves exactly as before, otherwise use the first variant.
fn fallback_variant(tokens: &Tokens) -> &Variant {
    tokens
        .variants()
        .find(|(_, v)| v.const_name == "GRUVBOX_DARK")
        .or_else(|| tokens.variants().next())
        .map(|(_, v)| v)
        .expect("validated tokens always have at least one variant")
}
