//! `generated/palette.schema.json` — a JSON Schema describing a family file.
//!
//! Derived from the same `Palette::FIELDS` list the emitters use, so editors
//! validating `tokens/families/*.toml` can never disagree with the generator.

use serde_json::{json, Map, Value};

use crate::model::Palette;

const HEX: &str = "^#[0-9a-f]{6}$";

pub fn render() -> Value {
    let mut palette_props = Map::new();
    for field in Palette::FIELDS {
        palette_props.insert(
            field.name.to_string(),
            json!({
                "type": "string",
                "pattern": HEX,
                "description": format!(
                    "{} role, exposed to CSS as {}.",
                    field.group, field.css_var()
                ),
            }),
        );
    }
    let required: Vec<&str> = Palette::FIELDS.iter().map(|f| f.name).collect();

    let label = json!({
        "type": "object",
        "description": "Display string. Both locales are mandatory.",
        "properties": { "fr": { "type": "string", "minLength": 1 },
                        "en": { "type": "string", "minLength": 1 } },
        "required": ["fr", "en"],
        "additionalProperties": false,
    });

    json!({
        "$schema": "https://json-schema.org/draft/2020-12/schema",
        "$id": "https://github.com/Project-Colony/Project-Colony-Resources/generated/palette.schema.json",
        "title": "Project Colony theme family",
        "description":
            "@generated by colony-tokens — DO NOT EDIT. Validates tokens/families/*.toml.",
        "type": "object",
        "properties": {
            "key": {
                "type": "string",
                "pattern": "^[a-z0-9_]+$",
                "description": "Stable family key. Must equal the file name.",
            },
            "order": {
                "type": "integer",
                "minimum": 1,
                "description": "Position in the Settings picker. Unique across families.",
            },
            "label_key": { "type": "string", "pattern": "^[a-z0-9_]+$" },
            "icon": {
                "type": "string",
                "pattern": "^([0-9a-f]+)?$",
                "description": "Nerd Font codepoint as bare lowercase hex, or empty for none.",
            },
            "label": label,
            "notes": {
                "type": "string",
                "description": "Provenance and licensing context for the family.",
            },
            "variants": {
                "type": "array",
                "minItems": 1,
                "items": {
                    "type": "object",
                    "properties": {
                        "key": { "type": "string", "pattern": "^[a-z0-9_]+$" },
                        "const": {
                            "type": "string",
                            "pattern": "^[A-Z0-9_]+$",
                            "description":
                                "Rust const name. Renaming one breaks every consumer that pins it.",
                        },
                        "label_key": { "type": "string", "pattern": "^[a-z0-9_]+$" },
                        "mode": {
                            "enum": ["light", "dark"],
                            "description":
                                "Must agree with bg_primary's luminance; the generator checks it.",
                        },
                        "label": label,
                        "notes": {
                            "type": "string",
                            "description": "Why this palette looks the way it does.",
                        },
                        "swatch": {
                            "type": "object",
                            "description": "The two colours drawn on the picker card.",
                            "properties": {
                                "bg": { "type": "string", "pattern": HEX },
                                "accent": { "type": "string", "pattern": HEX },
                            },
                            "required": ["bg", "accent"],
                            "additionalProperties": false,
                        },
                        "palette": {
                            "type": "object",
                            "description": format!(
                                "All {} palette fields. None may be omitted.",
                                Palette::FIELDS.len()
                            ),
                            "properties": Value::Object(palette_props),
                            "required": required,
                            "additionalProperties": false,
                        },
                    },
                    "required": ["key", "const", "label_key", "mode", "label", "swatch", "palette"],
                    "additionalProperties": false,
                },
            },
        },
        "required": ["key", "order", "label_key", "icon", "label", "variants"],
        "additionalProperties": false,
    })
}
